### PR TITLE
updating help command

### PR DESCRIPTION
**Pull request by TheMoksej**
this should be good temporarily. I'll try to work on automated help when I won't be lazy and will have time.

This is how it'd look: https://canary.discordapp.com/channels/568567800910839811/663218985793224704/749758939830288464

I'd prefer this tho: https://canary.discordapp.com/channels/568567800910839811/663218985793224704/749761846403137547

### CODE REVIEW

**Comment by Cairo2k18** [comment]
I'll just leave this here and let you update it with the automated help when you can

**Comment by TheMoksej** [comment]
sure thing

**Comment by TheMoksej** [comment]
I hope I didn't mess up anything

**Comment by Cairo2k18** [comment]
I'll look at this in the next major release, ty mok

**Pull request closed without merging**
