### PR TITLE
added automod

### PR DESCRIPTION
**Pull request by TheMoksej**
Currently this has anti invite and anti spam. I don't know what you want me to add next to that.

I've tested **multiple** times, it is working, so if it breaks, blame yourself not me, I repeat - blame yourself.

### CODE REVIEW

**Comment by TheMoksej** [comment]
I've also added `status.py` file, so you wouldn't need to make one yourself haha

**Comment by TheMoksej** [comment]
Oh and yes, this doesn't have the check to see if member is trying to evade the mute be rejoining the server, but that's fairly simple to add, however, you'll need to use cache for that. If anything is missing from automod side, just lmk and I'll add that in, although I don't think we talked about anything else. Have fun.

~ Mok

**Comment by TheMoksej** [comment]
I forgot to add whitelisted invites into the list, please give me a day or two so I could fix that issue. I'll draft this pr whilst adding whitelisted invites

**Comment by TheMoksej** [comment]
Alright, should be good to go. I've tested once again, it does work, however if user spams the whitelisted invites with random invites, it might take a few seconds to delete because of the loops, but that shouldn't be problem because:
1) there's anti spam
2) They can send a maximum of 5 invites in 60 seconds, so they shouldn't be able to spam too much

**Comment by TheMoksej** [comment]
Marking this as draft until I re-do everything,

**Comment by Cairo2k18** [comment]
> Marking this as draft until I re-do everything.

tell me when you finish on this and i'll implement etc

**Comment by TheMoksej** [comment]
Same with this one. Will be introducing this in the rewrite.

**Pull request closed without merging**
