### PR TITLE
Do not need ping pong paddle.

### PR DESCRIPTION
**Pull request by shayypy**
The current ping pong paddle reaction is completely unneeded as there is already a ping pong paddle in the message. The extra request to discord is superfluous in every manner and should be minimized.

### CODE REVIEW

**Comment by Cairo2k18** [comment]
WE MUST HAVE PING PONG PADDLE

**Comment by shayypy** [comment]
NO. PING PONG PADDLE BAD

**Comment by Cairo2k18** [comment]
NO WE MUST HAVE PING PONG PADDLE!!!!!

**Comment by shayypy** [comment]
I AM AFRAID I WILL HAVE TO STOP USING DEL IF YOU DO NOT REMOVE THIS PING POND PADDLE AT ONCE!! THIS IS AN OUTRAGE

**Review by Cairo2k18 — CHANGES_REQUESTED** [review]
bad pr - we must have almighty ping pong paddle

**Comment by Cairo2k18** [comment]
PING PONG PADDLE MANDATORY

**Comment by ImVaskel** [comment]
The ping pong paddle is needed, end of discussion.

**Comment by shayypy** [comment]
that's a matter of opinion and a bad one at that

**Comment by Cairo2k18** [comment]
it is needed

**Comment by Cairo2k18** [comment]
> that's a matter of opinion and a bad one at that

bad boy

**Comment by shayypy** [comment]
this is irregular abuse of power i will have you report you to the blob council lest you remove the ping pong paddle

**Pull request closed without merging**
